config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root :to => "money#index"

  resources :users, except: [:show, :index]
  resources :reports
  resources :money do
    collection do
      get :refresh_rates
    end
  end

end

app/models/currency.rb
class Currency < ActiveRecord::Base
  belongs_to :exchange
  
end

app/models/exchange.rb
class Exchange < ActiveRecord::Base
  require 'open-uri'
  require 'nokogiri'

  def self.get_nbp_xml(date)
    xml = Nokogiri::XML(open("http://www.nbp.pl/kursy/xml/LastC.xml"))
    xml.search('pozycja').map do |position|
      %w[nazwa_waluty przelicznik kod_waluty kurs_kupna kurs_sprzedazy].each_with_object({}) do |n, o|
        o[n] = position.at(n).text
      end
    end
  end

  def self.save_xml_data(date)
    currency_hash = get_nbp_xml(date)

    if currency_hash.present?
      exchange = Exchange.create(name: date.strftime("%d-%m-%Y"))
      currency_hash.each do |currency| 
        Currency.create(name: currency['nazwa_waluty'], converter: currency['przelicznik'], code: currency['kod_waluty'], 
                        buy_price: currency['kurs_kupna'].to_s.gsub(',', '.'), sell_price: currency['kurs_sprzedazy'].to_s.gsub(',', '.'),
                        exchange_id: exchange.id)
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/money_controller.rb
class MoneyController < ApplicationController
  def index
    @exchanges = Exchange.order("created_at DESC").page(params[:page]).per_page(10)
  end

  def show
    @currency = Currency.where(exchange_id: (params[:id]))
  end

  def refresh_rates
    exchange_time = Time.now - 8.hour - 15.minutes

    if Exchange.last.present?
      if Exchange.last.created_at.strftime("%y%m%d") == Time.now.strftime("%y%m%d")
        flash[:notice] = 'Everything is up to date.'
      else
        Exchange.save_xml_data(exchange_time)
      end
    else
      Exchange.save_xml_data(exchange_time)
      flash[:notice] = 'Results were updated.'
    end

    redirect_to money_index_path
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def show
    @currency = Currency.where(code: (params[:id])).order("id DESC").page(params[:page]).per_page(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
  def average(*args)
    args.inject(:+).to_f / args.size
  end
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
  <li><%= link_to 'Money', money_index_path %></li>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Currency Status'
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      - if user_signed_in?
        .navbar
          .container
            .small{:style => "text-align:right"}
              = "Logged in as #{current_user.email}"
              = link_to "Logout", destroy_user_session_path, method: :delete
              = render 'layouts/messages'
      - else
        .h2
          = link_to "Sign up", new_user_registration_path
          = " or "
          = link_to "Login", new_user_session_path
          = " to continue."
      = yield

app/views/money/index.haml
- if user_signed_in?
  %div.container
    = link_to "Refresh", :controller => "money", :action => "refresh_rates"
    = will_paginate @exchanges
    %table.table
      - for exchange in @exchanges
        %tr
          %td=exchange.name
          %td=link_to "Details", money_path(exchange.id)

app/views/money/show.haml
- if user_signed_in?
  %div.container
    %table.table
      %thead
        %tr
          %td Currency
          %td Code
          %td Buy price
          %td Sell price
          %td 
      -@currency.each do |info|
        %tr
          %td=link_to info.name, report_path(info.code) 
          %td=info.code
          %td=info.buy_price
          %td=info.sell_price

app/views/reports/show.haml
%div.container
  %b=@currency.first.code
  = will_paginate @currency
  %table.table
    %thead
      %tr
        %td Date
        %td Buy Price
        %td Sell Price
        %td Average price
    - for t in @currency
      %tr
        %td=link_to t.exchange.created_at.strftime("%d.%m.%Y"), money_path(t.exchange.id)
        %td=t.buy_price
        %td=t.sell_price
        %td=average(t.buy_price, t.sell_price).round(4)